Data_Api: "kaggle datasets download -d uciml/sms-spam-collection-dataset"

columns_name:
  feature: "Text_Message"
  label: "Target"

columns:
      - Text_Message
      - Target

columns_data_type:
      Text_Message: 'object'
      Target: 'int'
