model_name: 'model.h5'
training_history: 'training_history.json'
accuracy_threshold: .85
model_params:
  data_processing:
    max_words: 6000
    max_sequence_length: 60

  model_training:
    epochs: 30
    batch_size: 32
    out_put_activation: 'sigmoid'
    hidden_activation: 'relu'
    dropout: 0.2
    optimizer: 'adam'
    loss: 'binary_crossentropy'
    validation_split: 0.2
    patience: 3
    embedding_dim: 50
    nurons_unit: 64
 
  
